In [8]:
import numpy as np
import pandas as pd

# Numpy and Pandas with examples

## Read/Write to various file formats

### From CSV

In [9]:
df = pd.read_csv('../datasets/employes.csv')
df

Name  Salary
0   Ivan    1000
1  Pesho    1200
2  Maria    2200

### From JSON

In [10]:
authors_json_df = pd.read_json('../datasets/authors.json')
authors_json_df.head(10)

author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/
5  B. Miller & D. Ranum                       http://reputablejournal.com/
6           Zed A. Shaw                  http://learnpythonthehardway.org/
7          Mark Pilgrim             http://getpython3.com/diveintopython3/
8          Mark Pilgrim             http://getpython3.com/diveintopython3/
9       Allen B. Downey                      http://www.greenteapress.com/

### From SQL

Make sure you have created the database and the user. If you want to follow the examples, you can import '../../datasets/sql_dbs/python_books.sql' like:

`mysql -u userName -p -f < python_books.sql`

In [11]:
from sqlalchemy import create_engine
import pymysql

# create_engine(dialect+driver://username:password@host:port/database)
sql_engine = create_engine('mysql+pymysql://test:test1234@localhost/TestDB', pool_recycle=3600)
dbConn = sql_engine.connect()

authors_sql_df = pd.read_sql("select * from python_books", dbConn);
authors_sql_df.head(10)


id                author  \
0  151           TEST AUTHOR   
1  152           Mike Pirnat   
2  153           David Mertz   
3  154       Muhammad Yasoob   
4  155  B. Miller & D. Ranum   
5  156     Jeffrey Elkner...   
6  157  B. Miller & D. Ranum   
7  158           Zed A. Shaw   
8  159          Mark Pilgrim   
9  160          Mark Pilgrim   

                                           authorUrl  
0                                           TEST URL  
1                            http://mike.pirnat.com/  
2  http://www.oreilly.com/programming/free/functi...  
3                             http://pythontips.com/  
4                        http://reputablejournal.com  
5                          http://greenteapress.com/  
6                       http://reputablejournal.com/  
7                  http://learnpythonthehardway.org/  
8             http://getpython3.com/diveintopython3/  
9             http://getpython3.com/diveintopython3/

### To CSV

In [12]:
# read from json
authors_json_df = pd.read_json('../datasets/authors.json')
authors_json_df.head(10)

# write to CSV:
authors_json_df.to_csv('authors.csv', sep=',', encoding='utf-8', index=False)

# let's check the file
authors_csv_df = pd.read_csv('./authors.csv')
authors_csv_df.head(8)

author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/
5  B. Miller & D. Ranum                       http://reputablejournal.com/
6           Zed A. Shaw                  http://learnpythonthehardway.org/
7          Mark Pilgrim             http://getpython3.com/diveintopython3/

## Analyse  data in a DataFrame

In [13]:
# remind the nap dataframe
authors_csv_df.head()

author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/

In [14]:
# check for missing (NaN) values
authors_csv_df.isna().sum()

author       0
authorUrl    0
dtype: int64

In [15]:
# get df detailed info:
authors_csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 2 columns):
author       75 non-null object
authorUrl    75 non-null object
dtypes: object(2)
memory usage: 1.3+ KB


## Search data in DataFrame

In [16]:
# authors_csv_df['author']
authors_csv_df.author

0              Mike Pirnat
1              David Mertz
2          Muhammad Yasoob
3     B. Miller & D. Ranum
4        Jeffrey Elkner...
              ...         
70                 Tim Cox
71       Massimo Di Pierro
72    Charles R. Severance
73          Caleb Hattingh
74             John Hearty
Name: author, Length: 75, dtype: object

In [17]:
# search string in cells:
import re
regex = re.compile(r'je', re.IGNORECASE)

mask = authors_csv_df.author.str.contains(regex)

authors_csv_df[mask]

author                  authorUrl
4   Jeffrey Elkner...  http://greenteapress.com/
36       Jesse Noller    http://jessenoller.com/

## Numpy demos

In [18]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
m.dtype

dtype('int64')

In [20]:
# element-wise operation
m_new = m+2
m_new

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# indexing and slicing
print(m)
# get second row from m:
# print(m[1])

# get second column from m:
# m[row_index,column_index]

second_column = m[:,1]
print(second_column.shape)
print(second_column)

# get 5,6,8,9
sliced = m[1:,1:]
sliced

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3,)
[2 5 8]


array([[5, 6],
       [8, 9]])

In [23]:
# create Series

s1 = pd.Series(np.arange(1,6))
s2 = pd.Series(['a','b','c','d','e'])
print(s1, s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64 0    a
1    b
2    c
3    d
4    e
dtype: object


In [24]:
df = pd.DataFrame(data={
    'A': s1,
    'B': s2
})
df

A  B
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e

In [25]:
# use this if you have spaces in names
df['A']

df['B'][1:4]

1    b
2    c
3    d
Name: B, dtype: object